homepage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/',views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout')
]

website/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

boards/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

boards/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

homepage/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import login, authenticate,logout

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

response = {}

def login_page(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            response['username'] = username
            return redirect("/login/")
        else:
            return HttpResponse("invalid username or password")
    else:
        return render(request, 'account.html', response)

def logout_page(request):
    request.session.flush()
    logout(request)
    return redirect("/login/")

homepage/templates/_partials/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>nethania sonya</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light col-md-12" style="background-color: #9AC2D3!important">
        <a class="navbar-brand" href="{% url 'homepage:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#education">Education</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#skills">Skills</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#experiences">Experiences</a>
            </li>
            <li>
                <button type="button" class="btn cbtn button" onclick="window.location.href='{% url 'homepage:contact' %}'">Contact</button>
            </li>
            <li>
                <button type="button" class="btn cbtn button" onclick="window.location.href='{% url 'homepage:login' %}'">Account</button>
            </li>
            </ul>
        </div>
    </nav> 

    {% block content %}
    {% endblock %}
</body>
</html>

homepage/templates/about.html
{% extends '_partials/master.html' %}
{% load static %}

    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <img src="{% static 'images/poto.png' %}" alt="aq" class="photo">
            </div>
            <div class="col">
                <p class="intro-paragraph">Welcome to my personal website! This page is basically my resume, so feel free to scroll down and get to know more things about me. Here’s a few things about myself: I’m a second-year student at Universitas Indonesia and an aspiring developer. I’m excited to explore new things and xxx. Please do not hesitate to hit the contact button if you need to get in touch.</p>
            </div>
        </div>
    </div>

        <div>
            <div class="edu" id="education">
                <h3 class="pink">where i'm studying</h3>
                <p>Universitas Indonesia</p>
                <h3 class="pink">what i'm studying</h3>
                <p>Computer Science</p>
                <h3 class="pink">when i expect to graduate</h3>
                <p>2022</p>
            </div>
            <div class="skills" id="skills">
                <h3 class="rose">what i'm (hopefully) good at:</h3>
                <p><strong>Technical skills:</strong><br>Python, Java, JavaScript, HTML, CSS, Adobe Illustrator</p>
            </div>
            <div class="experiences" id="experiences">
                <h3 class="rose">what i've experienced</h3>
                <h4 class="pink">Work Experience</h4>
                <p>Software Development Analyst Intern<br>Accenture, Jakarta</p>
                <h4 class="pink">Organization Experiences</h4>
                
                    <p>Head of Creative Media and Documentation – DPM Fasilkom UI 2019</p>
                    <p>Staff of Public Relation – RISTEK Fasilkom UI 2019</p>
                
                <h4 class="pink">Committee Experiences</h4>
                
                    <p>PIC of Creative – Open House Fasilkom UI 2019</p>
                    <p>Staff of Playground – COMPFEST 11</p>
                
            </div>
        </div>

        <footer class="page-footer">
            <p class="pink">Copyright 2019 © Nethania Sonya.</p>
        </footer>

        {% endblock %}

homepage/templates/account.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>nethania sonya</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <button type="button" class="cbtn button" onclick="window.location.href='{% url 'homepage:about' %}'">back</button>

    {% if user.is_authenticated%}
        <div class="container">
        <h2>Hello, {{ username }}!</h2>
        <p><a href="{% url 'homepage:logout' %}"">logout</a></p>
        </div>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
            <label for="username">Username</label><br>
            <input type="text" name="username" id="username">
            <label for="password">Password</label><br>
            <input type="password" name="password" id="password">
            <input type="submit" name="submit" value="Login">
        </form>
    {% endif %}

</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>nethania sonya</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <img src="{% static 'images/asset7.png' %}" alt="aset" class="asset casset">
    <button type="button" class="cbtn button" onclick="window.location.href='{% url 'homepage:about' %}'">back</button>
    <div class="message">
        <h2 class="pink">what's on your mind?</h2>
        <form action="mailto:nethaniasonyavls@gmail.com">
            <textarea name="message" rows="10" cols="60" class="inputbox"></textarea><br>
            <input type="submit" class="sbtn lightgrey button">
        </form>
        <div class="contact" id="contact">
            <p class="pink">Let's get in touch! Find me on:</p>
            <div>
                <a href="https://instagram.com/nethaniasonya"><img src="{% static 'images/instagram.png' %}" alt="ig"></a>
                <a href="https://twitter.com/nethaniasonyaa"><img src="{% static 'images/twitter.png' %}" alt="twt"></a>
                <a href="https://linkedin.com/in/nethaniasonya"><img src="{% static 'images/linkedin.png' %}" alt="in"></a>
            </div>
            <p style="font-weight: 600">Or <a href="mailto:nethaniasonyavls@gmail.com" class="email" style="color:#F3EAF6; text-decoration: underline; font-weight: 600">send me an email.</a></p>
        </div>
    </div>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>nethania sonya</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="icon" href="./static/logo.png">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700,800&display=swap" rel="stylesheet">
</head>
<body>
    <img src="{% static 'images/asset1.png' %}" alt="aset" class="topleft">
    <img src="{% static 'images/asset2.png' %}" alt="aset" class="topright">
    <img src="{% static 'images/asset3.png' %}" alt="aset" class="bottomleft">
    <div class="landing">
        <div class="container">
            <h1 class="nethania lightgrey">nethania</h1>
            <h1 class="sonya violet">sonya</h1>
            <button type = "button" class="button aboutbtn pink" onclick="window.location.href='{% url 'homepage:about' %}'">get to know me</button>
        </div>
    </div>
</body>
</html>